apiVersion: v1
kind: Service
metadata:
  name: seating-service
spec:
  selector:
    app: seating-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
